services:
  monogs:
    build: .
    environment:
      - DISPLAY=${DISPLAY}             # For Linux
      - XAUTHORITY=/root/.Xauthority
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.Xauthority:/root/.Xauthority:ro
      - ./datasets:/MonoGS/datasets
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
volumes:
  datasets: