name: MonoGS
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8.16
  - cudatoolkit=11.7
  - plyfile=0.8.1
  - pip=22.3.1  
  - tqdm
  - pip:
    - opencv-python==4.8.1.78
    - munch
    - trimesh
    - evo==1.31.0
    - open3d==0.17.0
    - torchmetrics
    - imgviz
    - PyOpenGL
    - glfw
    - PyGLM
    - wandb
    - lpips
    - rich
    - ruff
    - submodules/simple-knn
    - submodules/diff-gaussian-rasterization